<table style='width:100%; height: 100%'>
    <tr>
        <td align='center' valign='center'>
            <h1>It is our first GM page!</h1>
        </td>
    </tr>
</table>
<h3>Here's a simple DB "console". Don't hesitate to try it!</h3>
<form action="/index/test" method="POST">
    <table>
        <tr>
            <td>Query:</td>
            <td rowspan="2"><textarea cols="40" rows="8" name="sql"></textarea></td>
        </tr>
        <tr>
            <td><input type="submit" value="Try this"></td>
        </tr>
    </table>
</form>