<table style='width:100%; height: 100%'>
    <tr>
        <td align='center' valign='center'>
            <h1>It is our first GM page!</h1>
        </td>
    </tr>
</table>
<h3>Here's "some" results:</h3>
<form action="/index/test" method="POST">
    <table>
        <tr>
            <td>Query:</td>
            <td rowspan="2"><textarea cols="40" rows="8" name="sql"><?=$this->sSQL?></textarea></td>
        </tr>
        <tr>
            <td><input type="submit" value="Try this"></td>
        </tr>
    </table>
</form>
<?if($this->sError):?>
    <h3>Something went wrong. Application returned the following error: <?=$this->sError?></h3>
<?else:?>
    <table style="border: 1px solid black">
    <?if(count($this->rgQuery)):?>
        <tr>
        <?foreach(array_keys($this->rgQuery[0]) as $sKey):?>
            <th><?=$sKey?></th>
        <?endforeach;?>
        </tr>
    <?endif;?>
    <?foreach($this->rgQuery as $rgQuery):?>
        <tr>
        <?foreach($rgQuery as $sKey=>$sValue):?>
            <td style="border-top: 1px solid black; border-left: 1px solid black;"><?=$sValue?></td>
        <?endforeach;?>
        </tr>
    <?endforeach?>
    </table>
<?endif;?>
